export const TOAST_MESSAGES = {
    LOGIN_SUCCESS: 'Login successful!',
    LOGIN_ERROR: 'An error occurred during login. Please check email and/or password.',
    NO_USER: 'No user found with this associated email. Please create an account.',
    ACCOUNT_EXISTS: 'An account with this email already exists. Please use a different email or try logging in.',
    SIGNUP_SUCCESS: 'Sign up successful! Please log in.',
    SIGNUP_ERROR: 'An error occurred during signup. Please try again.',
    LOGOUT_SUCCESS: 'You have been successfully logged out.',
    GENERIC_ERROR: 'An unexpected error occurred. Please try again.',
    FORM_VALIDATION_ERROR: 'Please check your input and try again.',
    UNAUTHORIZED: 'You are not authorized to perform this action.',
    SESSION_EXPIRED: 'Your session has expired. Please log in again.',
    EMAIL_IN_USE: 'Email alreaydy in use for this account',
    EMAIL_IN_USE_OTHER: 'Email is in use by a different user',
    EMAIL_CHANGED_SUCCESS: 'Email changed successully',
    EMAIL_ERROR: 'An error occurred while updating email',
    PASSWORD_SUCCESS: 'Password changed successfully',
    INCORRECT_CURRENT_PASSWORD: 'Current password is incorrect',
    PASSWORD_RESET_SENT: 'Password reset instructions have been sent to your email.',
    WRONG_PASSWORD: 'Incorrect password. Please try again.',
    PASSWORD_RESET_SUCCESS: 'Your password has been successfully reset.',
    PROFILE_UPDATE_SUCCESS: 'Your profile has been successfully updated.',
    PET_UPDATE_SUCCESS: 'Pet updated successfully',
    PET_UPDATE_FAIL: 'Update info failed, please try again',
    PET_DELETE_SUCCESS: 'Pet deleted successfully',
    PET_DELETE_FAIL: 'Pet failed to delete, please try again',
    PET_CREATED_SUCCESS: 'Pet added',
    PET_CREATED_FAIL: 'Pet creation failed, please try again',
};